# Generated by Django 2.2.3 on 2020-04-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200417_2223'),
        ('contact', '0002_auto_20200410_1621'),
    ]

    operations = [
    ]
