# Generated by Django 2.2.3 on 2020-04-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingdang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页banner', 'verbose_name_plural': '首页banner'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banner/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否显示该图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(max_length=100, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_info',
            field=models.CharField(default='', max_length=50, verbose_name='图片描述'),
        ),
    ]
