# Generated by Django 2.2.3 on 2020-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_breed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catparent',
            name='color',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='catparent',
            name='sex',
            field=models.CharField(choices=[('boy', 'boy'), ('girl', 'girl'), ('secret', 'secret')], default='secret', max_length=16),
        ),
    ]
