# Generated by Django 2.2.3 on 2020-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_breed', '0002_auto_20200322_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='catparent',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cat_parent/%Y/%m/%d/'),
        ),
    ]
