# Generated by Django 2.2.3 on 2020-04-18 04:42

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_breed', '0003_catparent_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catparent',
            options={'verbose_name': '猫妈猫爸', 'verbose_name_plural': '猫妈猫爸'},
        ),
        migrations.AlterModelOptions(
            name='catparentimg',
            options={'verbose_name': '图片表', 'verbose_name_plural': '图片表'},
        ),
        migrations.AlterField(
            model_name='catparent',
            name='color',
            field=models.CharField(default='', max_length=70, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='catparent',
            name='excerpt',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='catparent',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cat_parent/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='catparent',
            name='name',
            field=models.CharField(max_length=70, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='catparent',
            name='sex',
            field=models.CharField(choices=[('boy', 'boy'), ('girl', 'girl'), ('secret', 'secret')], default='secret', max_length=16, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='catparent',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='catparentimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cat_parent/%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
