# Generated by Django 2.2.3 on 2020-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterField(
            model_name='link',
            name='img',
            field=models.ImageField(upload_to='link/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkurl',
            field=models.URLField(max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
