# Generated by Django 2.2.3 on 2020-04-18 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('index', models.IntegerField(default=999)),
            ],
            options={
                'verbose_name': '图片展览类别',
                'verbose_name_plural': '图片展览类别',
            },
        ),
        migrations.CreateModel(
            name='ShowImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to='show_img/%Y/%m/%d/', verbose_name='封面图片')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cat_show.ShowCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '图片展览',
                'verbose_name_plural': '图片展览',
            },
        ),
    ]
