# Generated by Django 2.2.3 on 2020-04-18 04:54

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=70, verbose_name='名字')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('weichat', models.CharField(max_length=16, verbose_name='微信')),
                ('position', models.CharField(max_length=16, verbose_name='职业')),
                ('city', models.CharField(max_length=16, verbose_name='城市')),
                ('is_breed', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('is_guo', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('is_love', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
            ],
            options={
                'verbose_name': '用户购买猫信息',
                'verbose_name_plural': '用户购买猫信息',
            },
        ),
        migrations.CreateModel(
            name='CatBuyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cat_parent/%Y/%m/%d/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '小猫图片',
                'verbose_name_plural': '小猫图片',
            },
        ),
        migrations.CreateModel(
            name='CatBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=70, verbose_name='名字')),
                ('color', models.CharField(default='', max_length=70, verbose_name='颜色')),
                ('sex', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl'), ('secret', 'secret')], default='secret', max_length=16, verbose_name='性别')),
                ('excerpt', DjangoUeditor.models.UEditorField(blank=True, verbose_name='简介')),
                ('img', models.ImageField(blank=True, null=True, upload_to='cat_parent/%Y/%m/%d/', verbose_name='封面')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('imgs', models.ManyToManyField(blank=True, to='buy_cat.CatBuyImg')),
            ],
            options={
                'verbose_name': '代售小猫',
                'verbose_name_plural': '代售小猫',
            },
        ),
    ]
