# Generated by Django 2.2.3 on 2020-04-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catbuy',
            options={'verbose_name': '待售小猫', 'verbose_name_plural': '待售小猫'},
        ),
    ]
